name: RPG Items
main: think.rpgitems.Plugin
version: 3.0.4
dev-url: http://dev.bukkit.org/server-mods/rpg-items/
softdepend: [WorldGuard]
commands:
    rpgitem:
        description: RPG Items
        usage: 